### ISSUE TITLE
error after update -IterativeMixingKSamplerAdv.sample() got an unexpected keyword argument 'blending_function'

### ISSUE THREAD

**Issue by nikolaiusa** [ttulttul/ComfyUI-Iterative-Mixer#8] opened 2023-12-29 20:59 UTC
Error occurred when executing Iterative Mixing KSampler Advanced:

IterativeMixingKSamplerAdv.sample() got an unexpected keyword argument 'blending_function'

File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "I:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))

**Comment by if-ai** [comment] 2023-12-29 23:11
I have the same issue :(

**Comment by ttulttul** [comment] 2023-12-29 23:15
Please pull the latest commit.

**Comment by motelaus** [comment] 2023-12-29 23:53
> Please pull the latest commit.

I just did and was trying your newest example workflow and got that same error

**Comment by if-ai** [comment] 2023-12-30 00:09
![msedge_QUQRxLJqBl](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/21185218/2cbb2db9-1901-46d7-80f9-dfac9a8deb63)
Me too just updated and restarted still got the error on the same workflow that was working this morning with all the same settings :(

**Comment by if-ai** [comment] 2023-12-30 00:45
```
WARNING:root:blending schedule map: {'cosine': <class 'ComfyUI-Iterative-Mixer.nodes.CosineBlendingSchedule'>, 'linear': <class 'ComfyUI-Iterative-Mixer.nodes.LinearBlendingSchedule'>, 'logistic': <class 'ComfyUI-Iterative-Mixer.nodes.LogisticBlendingSchedule'>}
WARNING:root:blending function map: {'addition': <class 'ComfyUI-Iterative-Mixer.nodes.AdditiveBlendingFunction'>, 'norm_only': <class 'ComfyUI-Iterative-Mixer.nodes.NormOnlyBlendingFunction'>, 'slerp': <class 'ComfyUI-Iterative-Mixer.nodes.SLERPBlendingFunction'>}
```
The above message appears when initializing Comfy and then the one bellow when running the workflow

```
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/impactframes/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/impactframes/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/impactframes/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
TypeError: IterativeMixingKSamplerAdv.sample() got an unexpected keyword argument 'blending_function'
```

**Comment by ttulttul** [comment] 2023-12-30 00:58
The blending_function parameter was added to the node in the latest commit. Be sure to wipe out all trace of an older version, reload ComfyUI, and then also reload your workflow and make sure all the node values are set properly.

**Comment by motelaus** [comment] 2023-12-30 01:12
> The blending_function parameter was added to the node in the latest commit. Be sure to wipe out all trace of an older version, reload ComfyUI, and then also reload your workflow and make sure all the node values are set properly.

Tried all that and still getting that same error. Reinstalled the repo, used the new workflow, replaced the nodes in the new workflow -- still erroring with that message on the Iterative Mixing KSampler Advanced node.

**Comment by ttulttul** [comment] 2023-12-30 05:37
Would you mind sharing your JSON so that I can try to replicate?

**Comment by motelaus** [comment] 2023-12-30 06:22
I rolled back my install just to play with the nodes more, because it is a really cool/fun tool, but I have a tab open with the basic workflow I was testing with earlier:
[workflow(11).json](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/files/13797274/workflow.11.json)

**Comment by nikolaiusa** [comment] 2023-12-30 09:01
> Я откатил свою установку, чтобы больше поиграть с узлами, потому что это действительно крутой/забавный инструмент, но у меня открыта вкладка с базовым рабочим процессом, который я тестировал ранее: [workflow(11).json](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/files/13797274/workflow.11.json)
> 
> Может ли быть зависимость или что-то, что нужно установить? Кроме того, я использую последнее удобное обновление.

+1

**Comment by if-ai** [comment] 2023-12-30 10:08
> The blending_function parameter was added to the node in the latest commit. Be sure to wipe out all trace of an older version, reload ComfyUI, and then also reload your workflow and make sure all the node values are set properly.

I deleted the iterative mixer from my ComfyUI custom nodes and git cloned the latest again turned off and restarted the computer loaded the workflow I still get the error. I loaded the [4x Mixing Upscale.png](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/blob/main/examples/4x%20Mixing%20Upscale.png) and still get the same error after the batch unsampler on the iterative mixing ksampler advance #47
![msedge_QfeZB8CMXf](https://github.com/ttulttul/ComfyUI-Iterative-Mixer/assets/21185218/e86ef24a-9d88-4470-9364-56c232563133)

**Comment by if-ai** [comment] 2023-12-30 11:22
Nice I just fixed the error and made a PR is working wonderfully the new blending function fix many of the issues I had getting the results I wanted. Thank you also the readme is such a helpful and insightful document. Thank you so much.

**Comment by if-ai** [comment] 2023-12-30 16:06
I made a workflow using Iterative Mixer https://github.com/if-ai/IF-Animation-Workflows/blob/main/IF_4Up.json and also made a video about the WF made a video too  https://youtu.be/jwaCmaDMvpE?si=dgFcW0YsIRB4sb9U

**Comment by ttulttul** [comment] 2023-12-30 22:00
Apologies, everyone. I introduced a regression in the advanced node. This has been fixed in https://github.com/ttulttul/ComfyUI-Iterative-Mixer/commit/dd4dca003049637c63f01d196cb2696fc79e13fc

**Closed by ttulttul** 2023-12-30 22:00 UTC
